stages:
  - build
  - release

build:
  stage: build  
   only:
   - dev
  except:
   - tags
  before_script:
   - call restore-cache node_modules
  script:
   - call npm install
   - call npm run lint
   - call npm run test -- -c ci
   - call npm run build
  after_script:
   - call move-to-cache node_modules
  allow_failure: false

release:
  stage: release
  only:
   - dev
  before_script:
   - call restore-cache node_modules
  script:
   - call npm install
   - call npm run build
  after_script:
   - call move-to-cache node_modules
  when: manual
  allow_failure: false
